Squashed 'vision' changes from 7767e58e4..6c67243ef (#1330)
6c67243ef Merge pull request #871 from gouthamb/next
f390311d9 Update Makefile version
cb2a61c05 Merge pull request #860 from mounikk/AVFIRS
c25ff7203 stereo pipeline cosim fix
2744b7283 resolved merge conflict
dcefed049 resolved merge conflict
1a31a2e14 Merge pull request #869 from gouthamb/next
0396de15d To_fixed issue resolved
b91789886 Roll back to pre version
4b3164802 Resolve to_fixed issue
9b7931ab3 Resolve to_fixed issue
44153af60 Fix hsv2rgb input sizes
26476428b Merge pull request #868 from gouthamb/next
b9d2e0313 Merge branch 'FaaSApps:next' into next
af45b5926 Fix buffer size
fc9e3e78b Merge pull request #867 from gouthamb/next
2525601f5 Changed platform to VEK385
f8c827ed0 Merge pull request #866 from gouthamb/next
cd1e396ac Updated Makefile
abaa6c61d applied clang format
7d66be0d2 merge
7dc99932c Merge pull request #865 from gouthamb/next
8e5c2e69b Merge branch 'next' of https://gitenterprise.xilinx.com/gouthamb/xf_opencv into next
c31982edc Clang Standardization fix
e1147dad0 Merge pull request #864 from gouthamb/next
776c6dce5 Update Makefile
d9804abe7 Delete vitis.log
c0effaed4 Fix xclbin name
dc2432b96 Merge pull request #863 from gouthamb/next
05183fd79 Remove save-temps option
ffa4f24d0 Merge pull request #862 from gouthamb/next
70aa503a8 Reduce to 1 col
cdb861965 Merge branch 'FaaSApps:next' into next
b84eb4bb3 Resolve to_fixed() error
5af1ab127 Fix make file
1a8dd0651 fix the regression error AVFIRS, L2 stitch
61178caf2 Add AVFIRS doc
74f01267f updated remap doc
e5faf0201 updated the license
da6820ebd updated the license
10a2f433c fix the comments
f022719a0  Resolved the comments
c54b5eb6a Updated L2/examples opencl latency caluclation
23ad7540f update findcontour Doc
70c18d6ac Add stitch documentation
a76811b98 Add remap functionality to handle varying input and output resolutions
839591cc8 Add L3 AVFIRS function
aaccee3af Add L2/stitch function
cf0deb51f Add waitMat function
39161eb2f Add L1 stitch function

Co-authored-by: sdausr <sdausr@xilinx.com>

diff --git a/vision/L2/tests/ispstats/ispstats_NPPC1_16UC1_16UC1_ISPSTATS_BAYER/Makefile b/vision/L2/tests/ispstats/ispstats_NPPC1_16UC1_16UC1_ISPSTATS_BAYER/Makefile
--- a/vision/L2/tests/ispstats/ispstats_NPPC1_16UC1_16UC1_ISPSTATS_BAYER/Makefile
+++ b/vision/L2/tests/ispstats/ispstats_NPPC1_16UC1_16UC1_ISPSTATS_BAYER/Makefile
@@ -48,6 +48,10 @@ MK_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
 XF_PROJ_ROOT ?= $(shell bash -c 'export MK_PATH=$(MK_PATH); echo $${MK_PATH%/L2/*}')
 CUR_DIR := $(patsubst %/,%,$(dir $(MK_PATH)))
 XFLIB_DIR = $(XF_PROJ_ROOT)
+SCRIPTS_DIR := ${CUR_DIR}/scripts_mk
+VITIS_LIB_ROOT = $(dir $(XF_PROJ_ROOT))
+export XF_PROJ_ROOT
+export VITIS_LIB_ROOT
 
 # setting default value
 TARGET ?= hw_emu
@@ -57,7 +61,19 @@ ifeq ($(PLATFORM),)
 PLATFORM := $(DEVICE)
 endif
 ifeq ($(PLATFORM),)
-PLATFORM := vek280
+PLATFORM := vek385
+endif
+
+#setting SYSROOT
+ifneq (,$(findstring vek385, $(PLATFORM)))
+ifeq (,$(wildcard $(YOCTO_ARTIFACTS)))
+$(error YOCTO_ARTIFACTS ENV variable is not set, please set ENV variable correctly and rerun)
+endif
+export YOCTO_ARTIFACTS
+export SYSROOT = ${YOCTO_ARTIFACTS}/amd-cortexa78-mali-common_meta-edf-app-sdk/sdk/sysroots/cortexa72-cortexa53-amd-linux
+VPP_FLAGS_CFG += --part xc2ve3858-ssva2112-2MP-e-S
+else
+VPP_FLAGS_CFG += -t hw --platform $(XPLATFORM)
 endif
 
 # add warnning for sw_emu
@@ -65,7 +81,7 @@ ifeq ($(TARGET),sw_emu)
 $(error Error: The sw_emu target is no longer supported starting from 2025.1.)
 endif
 # #################### Checking if PLATFORM in whitelist ############################
-PLATFORM_ALLOWLIST += vek280
+PLATFORM_ALLOWLIST += vek385
 PLATFORM_BLOCKLIST += u280 u250 zcu104
 
 include ./utils.mk
@@ -102,7 +118,7 @@ VPP_FLAGS += $(EXTRA_VPP_FLAGS)
 ########################## Setting up Host Variables ##########################
 
 #Inclue Required Host Source Files
-ifneq (,$(shell echo $(XPLATFORM) | awk '/vek280/'))
+ifneq (,$(shell echo $(XPLATFORM) | awk '/vek385/'))
 HOST_SRCS += $(XFLIB_DIR)/L2/examples/ispstats/xf_ispstats_tb.cpp $(XFLIB_DIR)/ext/xcl2/xcl2.cpp 
 CXXFLAGS +=  -I $(SYSROOT)/usr/include -I $(SYSROOT)/usr/include/opencv4 -I $(XFLIB_DIR)/L2/tests/ispstats/ispstats_NPPC1_16UC1_16UC1_ISPSTATS_BAYER -I $(XFLIB_DIR)/ext/xcl2/ -I $(XFLIB_DIR)/L1/include
 CXXFLAGS += -O3 -I$(XILINX_HLS)/include -I$(XILINX_HLS)/include -I$(XILINX_HLS)/include
@@ -156,14 +172,29 @@ BINARY_CONTAINERS += $(BUILD_DIR)/krnl_ispstats.xclbin
 else
 BINARY_CONTAINERS += $(BUILD_DIR)/krnl_ispstats_pkg.$(LINK_TARGET_FMT)
 BINARY_CONTAINERS_PKG += $(BUILD_DIR)/krnl_ispstats.xclbin
+BINARY_NAME := krnl_ispstats
 endif
 
 # ################ Setting Rules for Binary Containers (Building Kernels) ################
-$(TEMP_DIR)/ispstats_accel.xo: $(XFLIB_DIR)/L2/examples/ispstats/xf_ispstats_accel.cpp 
+
+ifeq ($(wildcard hls_config_ispstats_accel.tmpl),)
+-include gen_param.mk
+endif
+$(TEMP_DIR)/ispstats_accel/ispstats_accel.xo: $(XFLIB_DIR)/L2/examples/ispstats/xf_ispstats_accel.cpp 
 	$(ECHO) "Compiling Kernel: ispstats_accel"
 	mkdir -p $(TEMP_DIR)
+ifeq ($(wildcard hls_config_ispstats_accel.tmpl),)
 	$(VPP) -c $(VPP_FLAGS_ispstats_accel) $(VPP_FLAGS) -k ispstats_accel -I'$(<D)' --temp_dir $(TEMP_DIR) --report_dir $(TEMP_REPORT_DIR) -o $@ $^
-BINARY_CONTAINER_krnl_ispstats_OBJS += $(TEMP_DIR)/ispstats_accel.xo
+else
+	set hls_config_ispstats_accel.tmpl hls_config_ispstats_accel.cfg && \
+	    printf '%s\n' "$$CONFIG_GEN_PY" > gen_config.py && \
+	    ${PYTHON3} gen_config.py \
+		hls_config_ispstats_accel.tmpl \
+		hls_config_ispstats_accel.cfg && \
+	    rm -f gen_config.py
+	$(VPP) -c --mode hls --config hls_config_ispstats_accel.cfg --work_dir $(TEMP_DIR)/ispstats_accel $(VPP_FLAGS_CFG)
+endif
+BINARY_CONTAINER_krnl_ispstats_OBJS += $(TEMP_DIR)/ispstats_accel/ispstats_accel.xo
 
 BINARY_CONTAINERS_DEPS += $(BINARY_CONTAINER_krnl_ispstats_OBJS) 
 $(BINARY_CONTAINERS): $(BINARY_CONTAINERS_DEPS)
@@ -190,7 +221,7 @@ ifeq ($(SD_CARD_NEEDED), on)
 RUN_SCRIPT := $(BUILD_DIR)/run_script.sh
 $(RUN_SCRIPT):
 	rm -rf $(RUN_SCRIPT)
-	@echo 'export LD_LIBRARY_PATH=/mnt:/tmp:$(LIBRARY_PATH)' >> $(RUN_SCRIPT)
+	@echo 'export LD_LIBRARY_PATH=/mnt:/tmp${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} ' >> $(RUN_SCRIPT)
 ifneq ($(filter hw_emu, $(TARGET)),)
 	@echo 'export XCL_EMULATION_MODE=$(TARGET)' >> $(RUN_SCRIPT)
 endif
@@ -199,17 +230,23 @@ endif
 	@echo 'if [ -f platform_desc.txt  ]; then' >> $(RUN_SCRIPT)
 	@echo '        cp platform_desc.txt /etc/xocl.txt' >> $(RUN_SCRIPT)
 	@echo 'fi' >> $(RUN_SCRIPT)
+ifneq (,$(findstring AIE2PS, $(AIE_TYPE)))
+	@echo 'echo "INFO: Load the pdi and dtbo using fpgautil"' >> $(RUN_SCRIPT)
+	@echo 'fpgautil -b $(BINARY_NAME).pdi -o ${BINARY_NAME}.dtbo' >> $(RUN_SCRIPT)
+endif
 	@echo './$(EXE_NAME) $(PKG_HOST_ARGS)' >> $(RUN_SCRIPT)
 	@echo 'return_code=$$?' >> $(RUN_SCRIPT)
 	@echo 'if [ $$return_code -ne 0 ]; then' >> $(RUN_SCRIPT)
-	@echo '        echo "ERROR: TEST FAILED, RC=$$return_code"' >> $(RUN_SCRIPT)
+	@echo '        echo "ERROR: TEST FAILED, RC=$$return_code "' >> $(RUN_SCRIPT)
 	@echo 'else' >> $(RUN_SCRIPT)
-	@echo '        echo "INFO: TEST PASSED, RC=0"' >> $(RUN_SCRIPT)
+	@echo '        echo "INFO: TEST PASSED, RC=0 "' >> $(RUN_SCRIPT)
 	@echo 'fi' >> $(RUN_SCRIPT)
 	@echo 'echo "INFO: Embedded host run completed."' >> $(RUN_SCRIPT)
 	@echo 'exit $$return_code' >> $(RUN_SCRIPT)
 DATA_FILE := $(XFLIB_DIR)/data/128x128_bayer.png $(XFLIB_DIR)/data/128x128.png $(XFLIB_DIR)/data/HD_bayer_16bit.png $(XFLIB_DIR)/data/ltm_input_HD.png $(custom_data_file)
 DATA_DIR := $(custom_data_dir)
+DATA_FILE := $(strip $(DATA_FILE))
+DATA_DIR := $(strip $(DATA_DIR))
 SD_FILES += $(RUN_SCRIPT)
 SD_FILES += $(EXE_FILE)
 SD_FILES += $(EMCONFIG)
@@ -219,33 +256,58 @@ SD_FILES_WITH_PREFIX = $(foreach sd_file,$(SD_FILES), $(if $(filter $(sd_file),$
 SD_DIRS_WITH_PREFIX = $(foreach sd_dir,$(DATA_DIR),--package.sd_dir $(sd_dir))
 PACKAGE_FILES := $(BINARY_CONTAINERS)
 PACKAGE_FILES += $(AIE_CONTAINER)
+PACKAGE_DIR := $(CUR_DIR)/package_$(TARGET)
+PACKAGE_DIR_HW := $(CUR_DIR)/package.$(TARGET)
 SD_CARD := $(CUR_DIR)/package_$(TARGET)
-$(SD_CARD): host xclbin $(RUN_SCRIPT) $(EMCONFIG) check_kimage check_rootfs
+$(PACKAGE_DIR): host xclbin $(RUN_SCRIPT) $(EMCONFIG) #check_kimage check_rootfs
 	@echo "Generating sd_card folder...."
-	mkdir -p $(SD_CARD)
+	mkdir -p $(PACKAGE_DIR)
 	chmod a+rx $(BUILD_DIR)/run_script.sh
 # 1. DFX HW Flow
 ifeq ($(dfx_hw), on)
 	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p $(PACKAGE_FILES) $(VPP_PACKAGE) -o $(BINARY_CONTAINERS_PKG)
-	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p --package.out_dir  $(SD_CARD) --package.rootfs $(ROOTFS) --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX) --package.sd_file $(BINARY_CONTAINERS_PKG)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p --package.out_dir  $(PACKAGE_DIR) --package.rootfs $(ROOTFS) --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX) --package.sd_file $(BINARY_CONTAINERS_PKG)
 	@echo "### ***** sd_card generation done! ***** ###"
 endif
 # 2. General Embeded flow
 ifeq ($(dfx_hw), off)
 ifeq ($(pcie_versal), off)
-	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -o $(BINARY_CONTAINERS_PKG) -p $(PACKAGE_FILES) $(VPP_PACKAGE) --package.out_dir  $(SD_CARD) --package.rootfs $(ROOTFS) --package.generate_sdcard --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX)
+ifneq (,$(findstring AIE2PS, $(AIE_TYPE)))
+	$(VPP) -s -t $(TARGET) -p -f $(PACKAGE_FILES) -o $(BINARY_CONTAINERS_PKG) $(VPP_PACKAGE) --package.out_dir $(PACKAGE_DIR)
+ifeq (${TARGET},hw)
+	@mkdir -p $(PACKAGE_DIR)/sd_card
+	@cp -rf $(PACKAGE_DIR)/${BINARY_NAME}.dtbo $(PACKAGE_DIR)/*.bif $(BINARY_CONTAINERS_PKG) $(EXE_FILE) $(RUN_SCRIPT) $(PACKAGE_DIR)/sd_card
+	mv $(PACKAGE_DIR)/${BINARY_NAME}.pdi $(PACKAGE_DIR)/sd_card/${BINARY_NAME}.pdi
+	@for dir in $(DATA_DIR); do \
+	    cp -r $$dir/* $(PACKAGE_DIR)/sd_card/ ; \
+	done
+	@for f in $(DATA_FILE); do \
+	    [ -e "$$f" ] && cp -r $$f $(PACKAGE_DIR)/sd_card/ ; \
+	done
+	@ln -sfn $(PACKAGE_DIR) $(PACKAGE_DIR_HW)
+endif	
+else
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -o $(BINARY_CONTAINERS_PKG) -p $(PACKAGE_FILES) $(VPP_PACKAGE) --package.out_dir  $(PACKAGE_DIR) --package.rootfs $(ROOTFS) --package.generate_sdcard --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX)
+endif
 	@echo "### ***** sd_card generation done! ***** ###"
 endif
 endif
 
 .PHONY: sd_card
-sd_card: $(SD_CARD)
+sd_card: $(PACKAGE_DIR)
 endif
 
 ############################## Setting Essential Checks and Building Rules ##############################
 RUN_DEPS += host xclbin $(EMCONFIG)
 ifeq ($(SD_CARD_NEEDED), on)
-RUN_DEPS += $(SD_CARD)
+ifneq (,$(findstring AIE2PS, $(AIE_TYPE)))
+RUN_DEPS += $(PACKAGE_DIR)
+ifeq ($(TARGET),hw_emu)
+RUN_DEPS += qemu_combined copy_wic
+endif
+else
+RUN_DEPS += $(PACKAGE_DIR)
+endif
 endif
 
 .PHONY: mkflag all run
@@ -272,9 +334,13 @@ else
 	
 endif
 else
+ifneq (,$(findstring AIE2PS, $(AIE_TYPE)))
+	cd ${PACKAGE_DIR} && ./launch_hw_emu.sh -qemu-config ${QEMU_COMBINED}/combined.qemuboot.conf -login "amd-edf" -password "amd-edf" -run-app " mount /dev/sda2 /media; cd /media; ls; bash $(notdir $(RUN_SCRIPT)) " 2>&1 | tee qemu_output.log
+else
 	@echo $(RUN_DEPS)
-	$(SD_CARD)/launch_$(TARGET).sh -no-reboot -run-app $(notdir $(RUN_SCRIPT)) 
-	grep "TEST PASSED, RC=0" $(SD_CARD)/qemu_output.log || exit 1
+	$(PACKAGE_DIR)/launch_$(TARGET).sh -no-reboot -run-app $(notdir $(RUN_SCRIPT)) 
+endif
+	grep "TEST PASSED, RC=0" $(PACKAGE_DIR)/qemu_output.log || exit 1
 	
 endif
 endif
@@ -296,6 +362,27 @@ else ifeq ($(HOST_ARCH), x86)
 else
 	$(ECHO) "Please copy the content of sd_card folder and data to an SD Card and run on the board"
 endif
+endif
+
+############################## qemu combined and config ##############################
+ifneq (,$(findstring AIE2PS, $(AIE_TYPE)))
+QEMU_COMBINED := ${PACKAGE_DIR}/base_camp_images
+QEMU_PREBUILT := amd-cortexa78-mali-common_vek385_qemu_prebuilt
+
+qemu_combined:
+	cd ${PACKAGE_DIR}; \
+	rm -rf ${QEMU_COMBINED}; \
+	mkdir -p ${QEMU_COMBINED}; \
+	cp -prf ${YOCTO_ARTIFACTS}/${QEMU_PREBUILT}/* ${QEMU_COMBINED}/.; 
+endif
+
+############################## copy files to quem ##############################
+ifneq (,$(findstring AIE2PS, $(AIE_TYPE)))
+PDI_DIR := ${PACKAGE_DIR}/${BINARY_NAME}.pdi
+DTBO_DIR := ${PACKAGE_DIR}/${BINARY_NAME}.dtbo
+WIC_PARTITION := edf-linux-disk-image-amd-cortexa78-mali-common.rootfs.wic.ufs:2
+copy_wic:
+	bash ${SCRIPTS_DIR}/run_copy_wic.sh ${BINARY_CONTAINERS_PKG} ${EXE_FILE} ${DTBO_DIR} ${PDI_DIR} ${RUN_SCRIPT} ${QEMU_COMBINED} ${WIC_PARTITION} "${DATA_DIR}" ${DATA_FILE}
 endif
 
 ############################## Setting Targets ##############################
