Squashed 'data_analytics' changes from b72a972..fd50162 (#1161)
fd50162 Fuzzy match python3 version from TA. (#484)
b29e01e Fuzzy match python3 version from TA. (#483)
9f94449 Merge pull request #480 from jingt/CR-1229398
b0b1481 change warning info in Makefile when deprecate sw_emu in Makefile and update the version of utils.mk (#482)
a2844fa Deprecate sw_emu from description.json and Makefile (#481)
36fd412 rm sw_emu
509e4c1 remove sw_emu
8fea625 Merge pull request #479 from qianqiao/next
7d405ba fix deadlock
94f3f0a fix deadlock

Co-authored-by: sdausr <sdausr@xilinx.com>

diff --git a/data_analytics/L3/tests/contains_test/Makefile b/data_analytics/L3/tests/contains_test/Makefile
--- a/data_analytics/L3/tests/contains_test/Makefile
+++ b/data_analytics/L3/tests/contains_test/Makefile
@@ -1,4 +1,3 @@
-#
 # Copyright 2022 Xilinx, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -12,104 +11,267 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#
+# vitis makefile-generator v2.0.10
 
-# ####################################### Help Section #####################################
+############################## Help Section ##############################
 .PHONY: help
 
 help::
 	$(ECHO) "Makefile Usage:"
-	$(ECHO) "  make clean "
+	$(ECHO) "  make all TARGET=<hw_emu> PLATFORM=<FPGA platform>"
+	$(ECHO) "      Command to generate the design for specified Target and Shell."
+	$(ECHO) ""
+	$(ECHO) "  make run TARGET=<hw_emu> PLATFORM=<FPGA platform>"
+	$(ECHO) "      Command to run application in emulation."
+	$(ECHO) ""
+	$(ECHO) "  NOTE: For embedded platform the following setup steps are required:"
+	$(ECHO) "      a.If the platform and common-image are downloaded from Xilinx Download Center(Suggested):"
+	$(ECHO) "        Run the sdk.sh script from the common-image directory to install sysroot using the command : ./sdk.sh -y -d ./ -p "
+	$(ECHO) "        Unzip the rootfs file : gunzip ./rootfs.ext4.gz"
+	$(ECHO) "        export SYSROOT=< path-to-platform-sysroot >"
+	$(ECHO) "      b.User could also define SYSROOT, K_IMAGE and ROOTFS by themselves: "
+	$(ECHO) "        export SYSROOT=< path-to-platform-sysroot >"
+	$(ECHO) "        export K_IMAGE=< path-to-Image-files >"
+	$(ECHO) "        export ROOTFS=< path-to-rootfs >"
+	$(ECHO) ""
+	$(ECHO) "  make clean"
 	$(ECHO) "      Command to remove the generated non-hardware files."
 	$(ECHO) ""
 	$(ECHO) "  make cleanall"
 	$(ECHO) "      Command to remove all the generated files."
 	$(ECHO) ""
-	$(ECHO) "  make run"
-	$(ECHO) "      Command to run application."
-	$(ECHO) ""
 
-# ######################### Include environment variables in utils.mk ####################
+############################## Setting up Project Variables ##############################
+
 MK_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
 XF_PROJ_ROOT ?= $(shell bash -c 'export MK_PATH=$(MK_PATH); echo $${MK_PATH%/L3/*}')
 CUR_DIR := $(patsubst %/,%,$(dir $(MK_PATH)))
 XFLIB_DIR = $(XF_PROJ_ROOT)
 
-BUILD_DIR := $(CUR_DIR)/build
+# setting default value
+TARGET ?= hw_emu
 
-# ###################### Setting up default value of HOST_ARCH ####################### 
-TARGET ?= sw_emu
-HOST_ARCH ?= x86
+#setting PLATFORM
+ifeq ($(PLATFORM),)
+PLATFORM := $(DEVICE)
+endif
+ifeq ($(PLATFORM),)
+PLATFORM := u200
+endif
 
-ARROW_PATH := $(CUR_DIR)/ext/arrow
-PYTHON_PATH := $(XILINX_VIVADO)/tps/lnx64/python-3.8.3
-NUMPY_PATH := $(PYTHON_PATH)/lib/python3.8/site-packages/numpy/core/include
-PY_CMD := $(PYTHON_PATH)/bin/python3.8
+# add warnning for sw_emu
+ifeq ($(TARGET),sw_emu)
+$(error Error: The sw_emu target is no longer supported starting from 2025.1.)
+endif
+# #################### Checking if PLATFORM in whitelist ############################
+PLATFORM_ALLOWLIST += u200
+PLATFORM_BLOCKLIST += zc
 
-# ######################### Setting up Host Variables #########################
-#Include Required Host Source Files
-SO_SRCS += $(XF_PROJ_ROOT)/L3/src/sw/geospatial/strtree_contains.cpp
-SO_SRCS += $(BUILD_DIR)/contains_wrap.cpp
-
-GCC_INTOOL := 8.3.0
-BINUTILS_INTOOL := 2.37
 include ./utils.mk
+TEMP_DIR := _x_temp.$(TARGET).$(PLATFORM_NAME)
+TEMP_REPORT_DIR := $(CUR_DIR)/reports/_x.$(TARGET).$(PLATFORM_NAME)
+BUILD_DIR := build_dir.$(TARGET).$(PLATFORM_NAME)
+ifneq ($(RESULT_DIR),)
+BUILD_DIR = $(RESULT_DIR)
+endif
+BUILD_REPORT_DIR := $(CUR_DIR)/reports/_build.$(TARGET).$(PLATFORM_NAME)
+EMCONFIG := $(BUILD_DIR)/emconfig.json
+XCLBIN_DIR := $(CUR_DIR)/$(BUILD_DIR)
+export XCL_BINDIR = $(XCLBIN_DIR)
 
-CXXFLAGS += -I$(CUR_DIR)/host
-CXXFLAGS += -I$(XF_PROJ_ROOT)/L3/include/sw/xf_data_analytics/geospatial
+EXE_FILE_DEPS :=
+BINARY_CONTAINERS_DEPS :=
+RUN_DEPS :=
 
-PYFLAGS += -I$(XF_PROJ_ROOT)/L3/include/sw/xf_data_analytics/geospatial
+# get global setting
+ifeq ($(HOST_ARCH), x86)
+CXXFLAGS += -fmessage-length=0 -I$(CUR_DIR)/src/ -I$(XILINX_XRT)/include -I$(XILINX_HLS)/include -std=c++14 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label 
+LDFLAGS += -pthread -L$(XILINX_XRT)/lib -L$(XILINX_HLS)/lnx64/tools/fpo_v7_1 -Wl,--as-needed -lOpenCL -lxrt_coreutil -lgmp -lmpfr -lIp_floating_point_v7_1_bitacc_cmodel 
+VPP_FLAGS += -t $(TARGET) --platform $(XPLATFORM) --save-temps 
+VPP_LDFLAGS += --optimize 2 -R 2 
+else ifeq ($(HOST_ARCH), aarch64)
+CXXFLAGS += -I$(CUR_DIR)/src/ -fmessage-length=0 --sysroot=$(SYSROOT)  -I$(SYSROOT)/usr/include/xrt -I$(XILINX_HLS)/include -std=c++14 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label 
+LDFLAGS += -pthread -L$(SYSROOT)/usr/lib -Wl,--as-needed -lxilinxopencl -lxrt_coreutil 
+VPP_FLAGS += -t $(TARGET) --platform $(XPLATFORM) --save-temps 
+VPP_LDFLAGS += --optimize 2 -R 2 
+endif
+CXXFLAGS += $(EXTRA_CXXFLAGS)
+VPP_FLAGS += $(EXTRA_VPP_FLAGS)
 
-CXXFLAGS += -I$(ARROW_PATH)/cpp/src
-CXXFLAGS += -I$(PYTHON_PATH)/include/python3.8 -I$(NUMPY_PATH)
-CXXFLAGS += -I$(XILINX_HLS)/include -std=c++11 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label
+########################## Setting up Host Variables ##########################
 
-LDFLAGS += -L$(ARROW_PATH)/cpp/release/release -larrow 
-LDFLAGS += -fopenmp
+#Inclue Required Host Source Files
+HOST_SRCS += 
+CXXFLAGS +=  -I $(XFLIB_DIR)/L1/include/sw -I $(XFLIB_DIR)/L3/include/sw -I $(XFLIB_DIR)/ext/xcl2 -I $(XFLIB_DIR)/../utils/L1/include
 
-LIBRARY_PATH = $(PYTHON_PATH)/lib:$(ARROW_PATH)/cpp/release/release:$(BUILD_DIR)
-PYPATH = $(BUILD_DIR):$(XF_PROJ_ROOT)/L3/src/sw/geospatial:$(CUR_DIR)/build:$(PYTHONPATH)
+# workaround for opencv
+ifeq (,$(findstring opencv,$(CXXFLAGS)))
+CXXFLAGS += $(XRT_CXXFLAGS)
+endif
 
-SO_FILE := $(BUILD_DIR)/_containsModule.so
-EXE_NAME := $(SO_FILE)
-all: $(EXE_NAME)
+EXE_NAME := 
+EXE_FILE := $(BUILD_DIR)/$(EXE_NAME)
+EXE_FILE_DEPS := $(HOST_SRCS) $(INSTANCE_FILES)  $(EXE_FILE_DEPS)
 
-PY_ARGS := $(CUR_DIR)/data/points.csv $(CUR_DIR)/data/zones.txt $(CUR_DIR)/data/golden.txt
-HOST_ARGS := -point $(CUR_DIR)/data/points.csv -polygon $(CUR_DIR)/data/zones.txt
+########################## Kernel compiler global settings ##########################
+VPP_FLAGS +=  -I $(XFLIB_DIR)/L1/include/hw -I $(XFLIB_DIR)/L2/include/hw
 
-# Dummy Vitis settings to pass Makefile checks
-VPP_FLAGS ?=
-VPP_LDFLAGS ?=
+######################### binary container global settings ##########################
 
-# ######################### Setting Targets of Makefile ################################
-.PHONY: run pre_build all
-
-CXX_PATH := $(patsubst %/,%,$(dir $(shell which $(CXX))))
-CMAKE_PATHS := $(sort $(wildcard $(XILINX_VITIS)/tps/lnx64/cmake-3.2*.*))
-CMAKE_PATH := $(word $(words $(CMAKE_PATHS)),$(CMAKE_PATHS))
-
-pre_build:
-	mkdir -p $(CUR_DIR)/ext
-	make -C $(XF_PROJ_ROOT)/ext/swig DEST_DIR=$(CUR_DIR)/ext
-	PATH=$(CMAKE_PATH)/bin:${PATH} && make -C $(XF_PROJ_ROOT)/ext/arrow DEST_DIR=$(CUR_DIR)/ext COMPILER_PATH=$(CXX_PATH)
-
-NUMPY_SRC := $(CUR_DIR)/host/numpy.i
-
-$(NUMPY_SRC):
-	wget https://raw.githubusercontent.com/numpy/numpy/maintenance/1.19.x/tools/swig/numpy.i -P $(CUR_DIR)/host
-
-$(SO_FILE): pre_build $(NUMPY_SRC) 
+############################## Setting Rules for Host (Building Host Executable) ##############################
+$(EXE_FILE): $(EXE_FILE_DEPS)
 	mkdir -p $(BUILD_DIR)
-	$(CUR_DIR)/ext/swig/install/bin/swig -c++ -python $(PYFLAGS) -o $(BUILD_DIR)/contains_wrap.cpp $(CUR_DIR)/host/contains.i
-	$(CXX) -fPIC -c $(SO_SRCS) $(CXXFLAGS) $(LDFLAGS)
-	$(CXX) -shared strtree_contains.o contains_wrap.o -o $(SO_FILE) $(CXXFLAGS) $(LDFLAGS)
+	$(CXX) -o $@ $(filter %.s %.c %.cc %.cpp %cxx, $^) $(CXXFLAGS) $(LDFLAGS)
 
-run: $(SO_FILE)
-	PYTHONPATH=$(PYPATH) LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH $(PY_CMD) $(CUR_DIR)/host/demo_start.py $(PY_ARGS)
+$(EMCONFIG):
+	emconfigutil --platform $(XPLATFORM) --od $(BUILD_DIR)
 
-clean:
-	rm -rf $(CUR_DIR)/build strtree_contains.o contains_wrap.o 
+############################## Package final xclbin or sd_card folder (for embedded) ##############################
+# AIE_ON_X86 Flow
+ifeq ($(pcie_versal), on)
+	@echo "### ***** running AIE ON_X86 ***** ###"
+	${VPP} -p $(VPP_PACKAGE) -t ${TARGET} -f ${XPLATFORM} ${AIE_CONTAINER} ${BINARY_CONTAINERS} -o $(BINARY_CONTAINERS_PKG) --package.boot_mode ospi
+	@echo "### ***** xclbin generation done! ***** ###"
+endif
 
-cleanall: clean
-	rm -rf $(NUMPY_SRC) ext 
+ifeq ($(SD_CARD_NEEDED), on)
+RUN_SCRIPT := $(BUILD_DIR)/run_script.sh
+$(RUN_SCRIPT):
+	rm -rf $(RUN_SCRIPT)
+	@echo 'export LD_LIBRARY_PATH=/mnt:/tmp:$(LIBRARY_PATH)' >> $(RUN_SCRIPT)
+ifneq ($(filter hw_emu, $(TARGET)),)
+	@echo 'export XCL_EMULATION_MODE=$(TARGET)' >> $(RUN_SCRIPT)
+endif
+	@echo 'export XILINX_VITIS=/mnt' >> $(RUN_SCRIPT)
+	@echo 'export XILINX_XRT=/usr' >> $(RUN_SCRIPT)
+	@echo 'if [ -f platform_desc.txt  ]; then' >> $(RUN_SCRIPT)
+	@echo '        cp platform_desc.txt /etc/xocl.txt' >> $(RUN_SCRIPT)
+	@echo 'fi' >> $(RUN_SCRIPT)
+	@echo './$(EXE_NAME) $(PKG_HOST_ARGS)' >> $(RUN_SCRIPT)
+	@echo 'return_code=$$?' >> $(RUN_SCRIPT)
+	@echo 'if [ $$return_code -ne 0 ]; then' >> $(RUN_SCRIPT)
+	@echo '        echo "ERROR: TEST FAILED, RC=$$return_code"' >> $(RUN_SCRIPT)
+	@echo 'else' >> $(RUN_SCRIPT)
+	@echo '        echo "INFO: TEST PASSED, RC=0"' >> $(RUN_SCRIPT)
+	@echo 'fi' >> $(RUN_SCRIPT)
+	@echo 'echo "INFO: Embedded host run completed."' >> $(RUN_SCRIPT)
+	@echo 'exit $$return_code' >> $(RUN_SCRIPT)
+DATA_FILE := $(custom_data_file)
+DATA_DIR := $(custom_data_dir)
+SD_FILES += $(RUN_SCRIPT)
+SD_FILES += $(EXE_FILE)
+SD_FILES += $(EMCONFIG)
+SD_FILES += xrt.ini
+SD_FILES += $(DATA_FILE)# where define DATAFILE in json
+SD_FILES_WITH_PREFIX = $(foreach sd_file,$(SD_FILES), $(if $(filter $(sd_file),$(wildcard $(sd_file))), --package.sd_file $(sd_file)))
+SD_DIRS_WITH_PREFIX = $(foreach sd_dir,$(DATA_DIR),--package.sd_dir $(sd_dir))
+PACKAGE_FILES := $(BINARY_CONTAINERS)
+PACKAGE_FILES += $(AIE_CONTAINER)
+SD_CARD := $(CUR_DIR)/package_$(TARGET)
+$(SD_CARD): host xclbin $(RUN_SCRIPT) $(EMCONFIG) check_kimage check_rootfs
+	@echo "Generating sd_card folder...."
+	mkdir -p $(SD_CARD)
+	chmod a+rx $(BUILD_DIR)/run_script.sh
+# 1. DFX HW Flow
+ifeq ($(dfx_hw), on)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p $(PACKAGE_FILES) $(VPP_PACKAGE) -o $(BINARY_CONTAINERS_PKG)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p --package.out_dir  $(SD_CARD) --package.rootfs $(ROOTFS) --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX) --package.sd_file $(BINARY_CONTAINERS_PKG)
+	@echo "### ***** sd_card generation done! ***** ###"
+endif
+# 2. General Embeded flow
+ifeq ($(dfx_hw), off)
+ifeq ($(pcie_versal), off)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -o $(BINARY_CONTAINERS_PKG) -p $(PACKAGE_FILES) $(VPP_PACKAGE) --package.out_dir  $(SD_CARD) --package.rootfs $(ROOTFS) --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX)
+	@echo "### ***** sd_card generation done! ***** ###"
+endif
+endif
 
+.PHONY: sd_card
+sd_card: $(SD_CARD)
+endif
+
+############################## Setting Essential Checks and Building Rules ##############################
+RUN_DEPS += host xclbin $(EMCONFIG)
+ifeq ($(SD_CARD_NEEDED), on)
+RUN_DEPS += $(SD_CARD)
+endif
+
+.PHONY: mkflag all run
+mkflag:
+	mkdir -p $(BUILD_DIR)
+	rm -rf $(BUILD_DIR)/makefile_args.txt
+	@for var in $(MAKEFLAGS); do echo $$var >> $(BUILD_DIR)/makefile_args.txt; done
+
+all: check_device check_vpp check_platform mkflag $(RUN_DEPS)
+
+run: all
+#hw_emu
+ifneq (,$(filter hw_emu, $(TARGET)))
+ifeq ($(HOST_ARCH), x86)
+ifeq ($(pcie_versal), on)
+	cp $(AIE_WORK_DIR)/reports/dma_lock_report.json ./
+	cp $(AIE_WORK_DIR)/ps/c_rts/aie_control_config.json ./
+	LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH \
+	XCL_EMULATION_MODE=$(TARGET) $(EXE_FILE) $(BINARY_CONTAINERS_PKG) $(HOST_ARGS) 
+	
+else
+	LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH \
+	XCL_EMULATION_MODE=$(TARGET) $(EXE_FILE) $(BINARY_CONTAINERS_PKG) $(HOST_ARGS)
+	
+endif
+else
+	@echo $(RUN_DEPS)
+	$(SD_CARD)/launch_$(TARGET).sh -no-reboot -run-app $(notdir $(RUN_SCRIPT)) 
+	grep "TEST PASSED, RC=0" $(SD_CARD)/qemu_output.log || exit 1
+	
+endif
+endif
+#hw
+ifeq ($(TARGET), hw)
+ifeq ($(HOST_ARCH), x86)
+	LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH \
+	$(EXE_FILE) $(HOST_ARGS)
+	
+else
+	$(ECHO) "Please copy the content of sd_card folder and data to an SD Card and run on the board"
+endif
+endif
+
+############################## Setting Targets ##############################
+
+.PHONY: clean cleanall emconfig valid_params
+emconfig: $(EMCONFIG)
+
+.PHONY: host
+ifeq ($(HOST_ARCH), x86)
+host: check_xrt   $(EXE_FILE)
+else
+host: check_sysroot   $(EXE_FILE)
+endif
+
+.PHONY: xclbin
+ifeq ($(HOST_ARCH), x86)
+xclbin: check_vpp check_xrt  $(BINARY_CONTAINERS)
+else
+xclbin: check_vpp check_sysroot  $(BINARY_CONTAINERS)
+endif
+
+#################### Parameterized File Generation ##########################
+
+gen_instances: $(GENERATED_FILES)
+
+############################## Cleaning Rules ##############################
+cleanh:
+	-$(RMDIR) $(EXE_FILE)  vitis_* TempConfig system_estimate.xtxt *.rpt .run/  $(INST_TB_FILES)
+	-$(RMDIR) src/*.ll _xocc_* .Xil dltmp* xmltmp* *.log *.jou *.wcfg *.wdb sample_link.ini sample_compile.ini obj*  bin* *.csv *.jpg *.jpeg *.png *.db
+
+cleank:
+	-$(RMDIR) $(BUILD_DIR)/*.xclbin _vimage *xclbin.run_summary qemu-memory-_* emulation/ _vimage/ pl*start_simulation. sh *.xclbin
+	-$(RMDIR) _x_temp.* _x* $(INST_FILES)
+
+cleanall: cleanh cleank
+	-$(RMDIR) $(BUILD_DIR)  emconfig.json *.html $(TEMP_DIR) $(CUR_DIR)/reports *.csv *.run_summary  $(CUR_DIR)/*.raw package_*   $(BUILD_DIR)/run_script.sh .ipcache *.str
+	-$(RMDIR)  $(AIE_WORK_DIR) $(AIE_PKG_DIR) $(CUR_DIR)/*.xpe $(CUR_DIR)/hw.o $(CUR_DIR)/*.xsa $(CUR_DIR)/xnwOut
+	-$(RMDIR)  *.html $(GENERATED_FILES)
+
+clean: cleanh
