Squashed 'dsp' changes from e4b818acb..018baa426 (#1149)
018baa426 Merge pull request #1750 from berry/dev2next_250417
94a72fda2 copy dev to next
34c42f1a6 Merge pull request #1741 from mlechtan/next
359b40151 Merge pull request #1740 from mlechtan/next_fir_casc_fix
81247ee95 dev2next 14042025
b00406adf FIRs Meta: Fix for TP_CASC_LEN check
31adc57d4 Merge pull request #1733 from berry/dev2next_250411
44b6a3d5a Merge pull request #1736 from FaaSApps/next_docs_tdm_typo_fix
7189deb61 Update func-fir-TDM.rst
103c88812 copy dev to next
18b5eaa00 Merge pull request #1732 from uvimalku/cr_fixes
02072e771 VSS FFT: Minor fixes
3647a8ec4 Merge pull request #1727 from berry/dev2next_250409
d075c14c6 copy dev to next
aded7734f Merge pull request #1722 from berry/dev2next_250402
25104e6a2 copy dev to next
05e808cd1 Merge pull request #1703 from berry/dev2next_250324
611b58e61 Delete graph_euclidean_distance_euclidean_distance.txt
8ee9e7e47 Merge branch 'next' into dev2next_250324
b0c56dc62 copy dev to next
24b5c1766 Merge pull request #1692 from berry/dev2next_250318
20fbd3fdb re rerun dev 2next
6bbc23f34 copy dev to next
bc664cb9d Merge pull request #1686 from liyuanz/replace_python
46c71c8a4 Merge branch 'next' into replace_python
df1520657 Merge pull request #1683 from berry/dev2next_250313
9039ad9c9 replace python path
29f0997dd copy dev to next
27bd3ce1d Merge pull request #1675 from berry/dev2next_250310
13a1203d0 comment out gen_out_files call
9290f7936 remove compare_out from next
475a2391f copy dev to next
8cbcd7418 Merge pull request #1667 from berry/dev2next_250228
0db2a2b5f copy dev to next
00a03b3c6 Merge pull request #1651 from liyuanz/deprecate_sw_system
6a3093b3f Merge pull request #1656 from berry/dev2next_250219
9018895db change warning
eae224921 change warning
600d8bc00 copy dev to next
584dff512 update utils.mk
e470d2368 update
fa900b4b9 deprecate sw_emu
add0597f4 Merge pull request #1638 from berry/dev2next_250206
fade83467 copy dev to next
330590040 Merge pull request #1620 from berry/dev2next_250121
a753a5a22 set default TP_PHASE_RELOAD_API to dds vmc tests
d610d8222 copy dev to next
3f0c90fc4 Merge pull request #1569 from liyuanz/add_time_aie
d6326e621 Fixing PR template tip example
d8fda937e Merge pull request #1591 from berry/dev2next_241128
79218c01b .
58002da54 removing "|& tee ..." from some helper mk files
3f1e9eadc copy dev (02d3292) to next
2788fe542 Merge pull request #1578 from mlechtan/next
84011578f FIR TDM: Add a clause to margin frame calculation
b513e1591 Merge pull request #1581 from FaaSApps/jenkinsfile_next
f1a4999c4 Update Jenkinsfile
fb962aaac FIR TDM: AIE1 optimization for evenFrames architecture
bc76f0016 change 2024.2_stable_latest to 2025.1_stable_latest
23321c236 add time for time out cases

Co-authored-by: sdausr <sdausr@xilinx.com>

diff --git a/dsp/L2/examples/vss_fft_ifft_1d/Makefile b/dsp/L2/examples/vss_fft_ifft_1d/Makefile
--- a/dsp/L2/examples/vss_fft_ifft_1d/Makefile
+++ b/dsp/L2/examples/vss_fft_ifft_1d/Makefile
@@ -1,6 +1,4 @@
-#
-# Copyright (C) 2019-2022, Xilinx, Inc.
-# Copyright (C) 2022-2024, Advanced Micro Devices, Inc.
+# Copyright (C) 2022-2025, Advanced Micro Devices, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -13,7 +11,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#
+# vitis makefile-generator v2.0.10
 
 ############################## Help Section ##############################
 .PHONY: help
@@ -61,9 +59,13 @@ ifeq ($(PLATFORM),)
 PLATFORM := vck190
 endif
 
+# add warnning for sw_emu
+ifeq ($(TARGET),sw_emu)
+$(error Error: The sw_emu target is no longer supported starting from 2025.1.)
+endif
 # #################### Checking if PLATFORM in whitelist ############################
-PLATFORM_ALLOWLIST += vck190 vek280
-PLATFORM_BLOCKLIST += 
+PLATFORM_ALLOWLIST += vck190
+PLATFORM_BLOCKLIST +=
 
 include ./utils.mk
 TEMP_DIR := _x_temp.$(TARGET).$(PLATFORM_NAME)
@@ -77,6 +79,123 @@ EMCONFIG := $(BUILD_DIR)/emconfig.json
 XCLBIN_DIR := $(CUR_DIR)/$(BUILD_DIR)
 export XCL_BINDIR = $(XCLBIN_DIR)
 
+EXE_FILE_DEPS :=
+BINARY_CONTAINERS_DEPS :=
+RUN_DEPS :=
+
+# get global setting
+ifeq ($(HOST_ARCH), x86)
+CXXFLAGS += -fmessage-length=0 -I$(CUR_DIR)/src/ -I$(XILINX_XRT)/include -I$(XILINX_HLS)/include -std=c++17 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label
+LDFLAGS += -pthread -L$(XILINX_XRT)/lib -L$(XILINX_HLS)/lnx64/tools/fpo_v7_1 -Wl,--as-needed -lOpenCL -lxrt_coreutil -lgmp -lmpfr -lIp_floating_point_v7_1_bitacc_cmodel
+VPP_FLAGS += -t $(TARGET) --platform $(XPLATFORM) --save-temps
+VPP_LDFLAGS += --optimize 2 -R 2
+else ifeq ($(HOST_ARCH), aarch64)
+CXXFLAGS += -I$(CUR_DIR)/src/ -fmessage-length=0 --sysroot=$(SYSROOT)  -I$(SYSROOT)/usr/include/xrt -I$(XILINX_HLS)/include -std=c++17 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label
+LDFLAGS += -pthread -L$(SYSROOT)/usr/lib -Wl,--as-needed -lxilinxopencl -lxrt_coreutil
+VPP_FLAGS += -t $(TARGET) --platform $(XPLATFORM) --save-temps
+VPP_LDFLAGS += --optimize 2 -R 2
+endif
+CXXFLAGS += $(EXTRA_CXXFLAGS)
+VPP_FLAGS += $(EXTRA_VPP_FLAGS)
+
+########################## Setting up Host Variables ##########################
+
+#Inclue Required Host Source Files
+HOST_SRCS +=
+CXXFLAGS +=  -I $(XFLIB_DIR)/L1/include/hw
+
+# workaround for opencv
+ifeq (,$(findstring opencv,$(CXXFLAGS)))
+CXXFLAGS += $(XRT_CXXFLAGS)
+endif
+
+EXE_NAME :=
+EXE_FILE := $(BUILD_DIR)/$(EXE_NAME)
+EXE_FILE_DEPS := $(HOST_SRCS) $(INSTANCE_FILES)  $(EXE_FILE_DEPS)
+
+########################## Kernel compiler global settings ##########################
+VPP_FLAGS +=  -I $(XFLIB_DIR)/L1/include/hw
+
+######################### binary container global settings ##########################
+
+############################## Setting Rules for Host (Building Host Executable) ##############################
+$(EXE_FILE): $(EXE_FILE_DEPS)
+	mkdir -p $(BUILD_DIR)
+	$(CXX) -o $@ $(filter %.s %.c %.cc %.cpp %cxx, $^) $(CXXFLAGS) $(LDFLAGS)
+
+$(EMCONFIG):
+	emconfigutil --platform $(XPLATFORM) --od $(BUILD_DIR)
+
+############################## Package final xclbin or sd_card folder (for embedded) ##############################
+# AIE_ON_X86 Flow
+ifeq ($(pcie_versal), on)
+	@echo "### ***** running AIE ON_X86 ***** ###"
+	${VPP} -p $(VPP_PACKAGE) -t ${TARGET} -f ${XPLATFORM} ${AIE_CONTAINER} ${BINARY_CONTAINERS} -o $(BINARY_CONTAINERS_PKG) --package.boot_mode ospi
+	@echo "### ***** xclbin generation done! ***** ###"
+endif
+
+ifeq ($(SD_CARD_NEEDED), on)
+RUN_SCRIPT := $(BUILD_DIR)/run_script.sh
+$(RUN_SCRIPT):
+	rm -rf $(RUN_SCRIPT)
+	@echo 'export LD_LIBRARY_PATH=/mnt:/tmp:$(LIBRARY_PATH)' >> $(RUN_SCRIPT)
+ifneq ($(filter hw_emu, $(TARGET)),)
+	@echo 'export XCL_EMULATION_MODE=$(TARGET)' >> $(RUN_SCRIPT)
+endif
+	@echo 'export XILINX_VITIS=/mnt' >> $(RUN_SCRIPT)
+	@echo 'export XILINX_XRT=/usr' >> $(RUN_SCRIPT)
+	@echo 'if [ -f platform_desc.txt  ]; then' >> $(RUN_SCRIPT)
+	@echo '        cp platform_desc.txt /etc/xocl.txt' >> $(RUN_SCRIPT)
+	@echo 'fi' >> $(RUN_SCRIPT)
+	@echo './$(EXE_NAME) $(PKG_HOST_ARGS)' >> $(RUN_SCRIPT)
+	@echo 'return_code=$$?' >> $(RUN_SCRIPT)
+	@echo 'if [ $$return_code -ne 0 ]; then' >> $(RUN_SCRIPT)
+	@echo '        echo "ERROR: TEST FAILED, RC=$$return_code"' >> $(RUN_SCRIPT)
+	@echo 'else' >> $(RUN_SCRIPT)
+	@echo '        echo "INFO: TEST PASSED, RC=0"' >> $(RUN_SCRIPT)
+	@echo 'fi' >> $(RUN_SCRIPT)
+	@echo 'echo "INFO: Embedded host run completed."' >> $(RUN_SCRIPT)
+	@echo 'exit $$return_code' >> $(RUN_SCRIPT)
+DATA_FILE := $(custom_data_file)
+DATA_DIR := $(custom_data_dir)
+SD_FILES += $(RUN_SCRIPT)
+SD_FILES += $(EXE_FILE)
+SD_FILES += $(EMCONFIG)
+SD_FILES += xrt.ini
+SD_FILES += $(DATA_FILE)# where define DATAFILE in json
+SD_FILES_WITH_PREFIX = $(foreach sd_file,$(SD_FILES), $(if $(filter $(sd_file),$(wildcard $(sd_file))), --package.sd_file $(sd_file)))
+SD_DIRS_WITH_PREFIX = $(foreach sd_dir,$(DATA_DIR),--package.sd_dir $(sd_dir))
+PACKAGE_FILES := $(BINARY_CONTAINERS)
+PACKAGE_FILES += $(AIE_CONTAINER)
+SD_CARD := $(CUR_DIR)/package_$(TARGET)
+$(SD_CARD): host xclbin $(RUN_SCRIPT) $(EMCONFIG) check_kimage check_rootfs
+	@echo "Generating sd_card folder...."
+	mkdir -p $(SD_CARD)
+	chmod a+rx $(BUILD_DIR)/run_script.sh
+# 1. DFX HW Flow
+ifeq ($(dfx_hw), on)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p $(PACKAGE_FILES) $(VPP_PACKAGE) -o $(BINARY_CONTAINERS_PKG)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -p --package.out_dir  $(SD_CARD) --package.rootfs $(ROOTFS) --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX) --package.sd_file $(BINARY_CONTAINERS_PKG)
+	@echo "### ***** sd_card generation done! ***** ###"
+endif
+# 2. General Embeded flow
+ifeq ($(dfx_hw), off)
+ifeq ($(pcie_versal), off)
+	$(VPP) -t $(TARGET) --platform $(XPLATFORM) -o $(BINARY_CONTAINERS_PKG) -p $(PACKAGE_FILES) $(VPP_PACKAGE) --package.out_dir  $(SD_CARD) --package.rootfs $(ROOTFS) --package.kernel_image $(K_IMAGE)  $(SD_FILES_WITH_PREFIX) $(SD_DIRS_WITH_PREFIX)
+	@echo "### ***** sd_card generation done! ***** ###"
+endif
+endif
+
+.PHONY: sd_card
+sd_card: $(SD_CARD)
+endif
+
+############################## Setting Essential Checks and Building Rules ##############################
+RUN_DEPS += pre_build
+#RUN_DEPS += host xclbin $(EMCONFIG)
+#ifeq ($(SD_CARD_NEEDED), on)
+#RUN_DEPS += $(SD_CARD)
+#endif
 
 .PHONY: mkflag all run
 mkflag:
@@ -84,9 +203,40 @@ mkflag:
 	rm -rf $(BUILD_DIR)/makefile_args.txt
 	@for var in $(MAKEFLAGS); do echo $$var >> $(BUILD_DIR)/makefile_args.txt; done
 
-all: check_device check_vpp check_platform mkflag
+all: check_device check_vpp check_platform mkflag $(RUN_DEPS)
 
-run: pre_build
+run: all
+#hw_emu
+ifneq (,$(filter hw_emu, $(TARGET)))
+ifeq ($(HOST_ARCH), x86)
+ifeq ($(pcie_versal), on)
+	cp $(AIE_WORK_DIR)/reports/dma_lock_report.json ./
+	cp $(AIE_WORK_DIR)/ps/c_rts/aie_control_config.json ./
+	LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH \
+	XCL_EMULATION_MODE=$(TARGET) $(EXE_FILE) $(BINARY_CONTAINERS_PKG) $(HOST_ARGS)
+
+else
+	LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH \
+	XCL_EMULATION_MODE=$(TARGET) $(EXE_FILE) $(BINARY_CONTAINERS_PKG) $(HOST_ARGS)
+
+endif
+else
+	@echo $(RUN_DEPS)
+	$(SD_CARD)/launch_$(TARGET).sh -no-reboot -run-app $(notdir $(RUN_SCRIPT))
+	grep "TEST PASSED, RC=0" $(SD_CARD)/qemu_output.log || exit 1
+
+endif
+endif
+#hw
+ifeq ($(TARGET), hw)
+ifeq ($(HOST_ARCH), x86)
+	LD_LIBRARY_PATH=$(LIBRARY_PATH):$$LD_LIBRARY_PATH \
+	$(EXE_FILE) $(HOST_ARGS)
+
+else
+	$(ECHO) "Please copy the content of sd_card folder and data to an SD Card and run on the board"
+endif
+endif
 
 ############################## Setting Targets ##############################
 .PHONY: pre_build
@@ -95,6 +245,20 @@ pre_build:
 
 .PHONY: clean cleanall emconfig valid_params
 emconfig: $(EMCONFIG)
+
+.PHONY: host
+ifeq ($(HOST_ARCH), x86)
+host: check_xrt  pre_build $(EXE_FILE)
+else
+host: check_sysroot  pre_build $(EXE_FILE)
+endif
+
+.PHONY: xclbin
+ifeq ($(HOST_ARCH), x86)
+xclbin: check_vpp check_xrt  pre_build $(BINARY_CONTAINERS)
+else
+xclbin: check_vpp check_sysroot  pre_build $(BINARY_CONTAINERS)
+endif
 
 #################### Parameterized File Generation ##########################
 
